### ISSUE TITLE
Module input name update - Affects recent SDXL modules

### ISSUE THREAD

**Issue by hlky** [FizzleDorf/AIT#15]
In my local version and the SDXL support PR to [facebookincubator/AITemplate](https://github.com/facebookincubator/AITemplate/pull/879) I renamed inputs from `inputN`.

All modules will be recompiled soon, this will include the new naming scheme, and enable 8px increment. Suggestions on resolutions, batch sizes etc that should be supported are welcome, and could be shared here or in a separate issue.

Name changes are described below and need to be applied in [`AITemplate/ait/inference.py`](https://github.com/FizzleDorf/AIT/blob/main/AITemplate/ait/inference.py).

To use the recent SDXL modules, I would recommend applying only the UNet changes and using the existing VAE modules, as the changes are less involved. Note that the changes will then be incompatible with existing UNet modules for v1 and v2.

Depending on how long compiling a new set takes, and how long adoption of new modules would take, it may be advantageous to implement some sort of compatibility check, the module has capability of returning the input and output name to index maps, I'll leave this open to comment, SM70/SM75 may take longer to replace although I'm not sure of their popularity.

### UNet
* [`input0`](https://github.com/FizzleDorf/AIT/blob/d315ba3adbbaf01776fff23e644088908ec06cb1/AITemplate/ait/inference.py#L71) -> `latent_model_input`
* [`input1`](https://github.com/FizzleDorf/AIT/blob/d315ba3adbbaf01776fff23e644088908ec06cb1/AITemplate/ait/inference.py#L74) -> `timesteps`
* [`input2`](https://github.com/FizzleDorf/AIT/blob/d315ba3adbbaf01776fff23e644088908ec06cb1/AITemplate/ait/inference.py#L75) -> `encoder_hidden_states`
* [`input3`](https://github.com/FizzleDorf/AIT/blob/d315ba3adbbaf01776fff23e644088908ec06cb1/AITemplate/ait/inference.py#L78) -> `class_labels` (unused by this plugin)

### VAE
* [`vae_input`](https://github.com/FizzleDorf/AIT/blob/d315ba3adbbaf01776fff23e644088908ec06cb1/AITemplate/ait/inference.py#L167) -> `pixels` when encode, `latent` when decode
* [`vae_sample`](https://github.com/FizzleDorf/AIT/blob/d315ba3adbbaf01776fff23e644088908ec06cb1/AITemplate/ait/inference.py#L173) -> `random_sample`, only used by encode

Note: [module selection for VAE](https://github.com/FizzleDorf/AIT/blob/d315ba3adbbaf01776fff23e644088908ec06cb1/AITemplate/AITemplate.py#L521) uses `v1`, meaning the recent VAE modules labelled with `sd`: `xl` will not be used, the main difference between the recent and existing is logging, they will still work.

### CLIP
Unused by this plugin, but it's `input0` -> `input_ids` and `input1` to `position_ids`

## New modules

Attached are fresh modules with new naming and 8px increment, batch 1, Windows, sm80
Note plugin does not support selection of refiner modules at this time.
VAE Decode and VAE Encode aren't versioned because it is compatible between v1, v2 and xl
The filename format for the is also different, {type}_{sd}_{max_resolution}, and the extension is .dll, minimum resolution is always 8px
There should be some group input on the filename format, and which resolutions and batch sizes will be supported, whether to get rid of the folders and put cuda version/os etc in the filename

[clip.zip](https://github.com/FizzleDorf/AIT/files/12299138/clip.zip)
[unet_control_v1.zip](https://github.com/FizzleDorf/AIT/files/12299140/unet_control_v1.zip)
[unet_v1.zip](https://github.com/FizzleDorf/AIT/files/12299143/unet_v1.zip)
[unet_v2.zip](https://github.com/FizzleDorf/AIT/files/12299144/unet_v2.zip)
[unet_xl.zip](https://github.com/FizzleDorf/AIT/files/12299145/unet_xl.zip)
[unet_xlr.zip](https://github.com/FizzleDorf/AIT/files/12299146/unet_xlr.zip)
[vae_decode.zip](https://github.com/FizzleDorf/AIT/files/12299148/vae_decode.zip)
[vae_encode.zip](https://github.com/FizzleDorf/AIT/files/12299149/vae_encode.zip)

These modules are also being hosted for my upcoming UI that uses AIT, over at [modules.diffuse.rs](https://modules.diffuse.rs/windows_sm80.json), that file `windows_sm80.json` contains info for Windows SM80 modules, there will be others following the same format when available (`linux_sm80.json`, `windows_sm75.json` etc), the modules themselves are hosted on the same domain i.e. [`sm80_unet_xlr_2048.dll.xz`](https://modules.diffuse.rs/sm80_unet_xlr_2048.dll.xz), linux modules will have `.so` extension.
This plugin can be changed to use this source, or modules can be rehosted from that source if desired.

**Comment by CyberTimon** [comment]
After renaming these suggested names, I get this error: 

```
Found 3 modules for linux xl sm80 1 1024 unet
Using b5caabe98aeb69bada9d1566c897aed66a84d4fb21f31482160d7ef9987f04fd
  0%|                                                                                                                                                                                | 0/20 [00:00<?, ?it/s]Got cutlass error: Error InternalError: Got cutlass error: Error Internal
  0%|                                                                                                                                                                                | 0/20 [00:00<?, ?it/s]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/home/cybertimon/Repositories/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/cybertimon/Repositories/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/cybertimon/Repositories/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/cybertimon/Repositories/ComfyUI/nodes.py", line 1206, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/cybertimon/Repositories/ComfyUI/custom_nodes/AIT/AITemplate/AITemplate.py", line 170, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/cybertimon/Repositories/ComfyUI/custom_nodes/AIT/AITemplate/AITemplate.py", line 304, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/cybertimon/Repositories/ComfyUI/comfy/samplers.py", line 716, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar)
  File "/home/cybertimon/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/cybertimon/Repositories/ComfyUI/comfy/k_diffusion/sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/home/cybertimon/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/cybertimon/Repositories/ComfyUI/comfy/samplers.py", line 319, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options, seed=seed)
  File "/home/cybertimon/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/cybertimon/Repositories/ComfyUI/comfy/k_diffusion/external.py", line 125, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/home/cybertimon/Repositories/ComfyUI/comfy/k_diffusion/external.py", line 151, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/home/cybertimon/Repositories/ComfyUI/comfy/samplers.py", line 307, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options, seed=seed)
  File "/home/cybertimon/Repositories/ComfyUI/comfy/samplers.py", line 285, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
  File "/home/cybertimon/Repositories/ComfyUI/comfy/samplers.py", line 262, in calc_cond_uncond_batch
    output = model_function(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/cybertimon/Repositories/ComfyUI/custom_nodes/AIT/AITemplate/ait/inference.py", line 43, in apply_model
    return unet_inference(
  File "/home/cybertimon/Repositories/ComfyUI/custom_nodes/AIT/AITemplate/ait/inference.py", line 98, in unet_inference
    exe_module.run_with_tensors(inputs, ys, graph_mode=False)
  File "/home/cybertimon/Repositories/ComfyUI/custom_nodes/AIT/AITemplate/ait/module/model.py", line 565, in run_with_tensors
    outputs_ait = self.run(
  File "/home/cybertimon/Repositories/ComfyUI/custom_nodes/AIT/AITemplate/ait/module/model.py", line 468, in run
    return self._run_impl(
  File "/home/cybertimon/Repositories/ComfyUI/custom_nodes/AIT/AITemplate/ait/module/model.py", line 407, in _run_impl
    self.DLL.AITemplateModelContainerRun(
  File "/home/cybertimon/Repositories/ComfyUI/custom_nodes/AIT/AITemplate/ait/module/model.py", line 211, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerRun
```

**Comment by CyberTimon** [comment]
Maybe we should delete the AIT extension and reinstall it. Then you could make a step by step tutorial what changes needs to be done to get it to work with SDXL. Only if you have time of course.

**Comment by hlky** [comment]
Yes there appears to be an issue with the Linux modules. Linux users will need to compile their own or try Windows until I have time to look into the issue. To note it is known that modules compiled on one distro may not work on another.

**Comment by CyberTimon** [comment]
ohh so I have to compile them on my buggy env 😆

**Comment by CyberTimon** [comment]
The strange part is that the other user on windows has the same input0 issue which I think is not related to the model. The SD 1.5 linux unet models work by the way on my system so I don't see a issue why it shouldn't work.

**Comment by Shaistrong** [comment]
> * [`input0`](https://github.com/FizzleDorf/AIT/blob/d315ba3adbbaf01776fff23e644088908ec06cb1/AITemplate/ait/inference.py#L71) -> `latent_model_input`
> * [`input1`](https://github.com/FizzleDorf/AIT/blob/d315ba3adbbaf01776fff23e644088908ec06cb1/AITemplate/ait/inference.py#L74) -> `timesteps`
> * [`input2`](https://github.com/FizzleDorf/AIT/blob/d315ba3adbbaf01776fff23e644088908ec06cb1/AITemplate/ait/inference.py#L75) -> `encoder_hidden_states`
> * [`input3`](https://github.com/FizzleDorf/AIT/blob/d315ba3adbbaf01776fff23e644088908ec06cb1/AITemplate/ait/inference.py#L78) -> `class_labels` (unused by this plugin)

I don't really understand this. the lines you mentioned have: `"input0": latent_model_input.permute((0, 2, 3, 1))` which I think is what you said is necessary..?

**Comment by hlky** [comment]
I'm not sure what is unclear, the current name on the line linked is to be changed to the new name
Current name -> New name
That section is regarding UNet, it says `input0` is renamed to `latent_model_input`, `input1` is renamed to `timesteps`, `input2` is renamed to `encoder_hidden_states` and you can safely ignore `input3`.
The new modules use the new name, to use them the input names in the code need to match the names used by the module.
This is described in the initial post.

**Comment by Shaistrong** [comment]
> I'm not sure what is unclear, the current name on the line linked is to be changed to the new name Current name -> New name That section is regarding UNet, it says `input0` is renamed to `latent_model_input`, `input1` is renamed to `timesteps`, `input2` is renamed to `encoder_hidden_states` and you can safely ignore `input3`. The new modules use the new name, to use them the input names in the code need to match the names used by the module. This is described in the initial post.

did that, now it does: `ValueError: Did not get correct number of inputs expected 4, got 3`

**Comment by Shaistrong** [comment]
okay, now it does the first stage perfectly with the speed boost, but when starting second stage it says in the terminal: `[20:42:19]: NVIDIA GeForce RTX 4070 Ti
[20:42:19]: AITemplate modules compiled by hlky
[20:42:20]: Error: SetConstant did not receive correct number of bytes for unbound constant time_embedding_linear_1_weight: expected 819200 but got 1179648. Check that the provided tensor's shape is correct.` @hlky

**Comment by hlky** [comment]
I can't say for certain due to the limited information provided regarding the second stage, however the `time_embedding_linear_1_weight` is part of UNet, its size is determined `block_out_channels`, as the error states it got a larger size than expected I believe you are attempting to use XL refiner, which is a different architecture to the base model and therefore incompatible with the modules you are using. You can compile modules for refiner yourself, or await precompiled modules being provided.

**Comment by Shaistrong** [comment]
> I can't say for certain due to the limited information provided regarding the second stage, however the `time_embedding_linear_1_weight` is part of UNet, its size is determined `block_out_channels`, as the error states it got a larger size than expected I believe you are attempting to use XL refiner, which is a different architecture to the base model and therefore incompatible with the modules you are using. You can compile modules for refiner yourself, or await precompiled modules being provided.

oh gotcha. for some reason I can't compile them myself, so I'll wait

**Comment by Shaistrong** [comment]
> I can't say for certain due to the limited information provided regarding the second stage, however the `time_embedding_linear_1_weight` is part of UNet, its size is determined `block_out_channels`, as the error states it got a larger size than expected I believe you are attempting to use XL refiner, which is a different architecture to the base model and therefore incompatible with the modules you are using. You can compile modules for refiner yourself, or await precompiled modules being provided.

are you sure it's a different architecture? I thought `modules.json` just didn't specify the refiner modules

**Comment by hlky** [comment]
[xl-base](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/unet/config.json)
[xl-refiner](https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/blob/main/unet/config.json)
It is a different architecture. Refiner modules will be available soon.

**Comment by Shaistrong** [comment]
> No change required, just use `--hf-hub-or-path stabilityai/stable-diffusion-xl-refiner-1.0` instead of `--hf-hub-or-path stabilityai/stable-diffusion-xl-base-1.0`.

is this with the built AIT dir you linked yesterday? if yes what is the directory I should run this?

**Comment by hlky** [comment]
Please refer to the documentation and comments on related issues for compilation instructions. Precompiled refiner modules will be available soon, please be patient.

**Comment by hlky** [comment]
Closing this as #19 is nearing completion.
