### ISSUE TITLE
BS?

### ISSUE THREAD

**Issue by Shaistrong** [FizzleDorf/AIT#35]
when will there be modules for custom batch sizes? I compiled my own, but I can't get the node to see them.

**Comment by Shaistrong** [comment]
@hlky I know you probably resolved this already- when compiling for any batch size other than 1 in your AITemplate repo it does this:
![image_2023-08-22_192906334](https://github.com/FizzleDorf/AIT/assets/73827899/59668137-446c-47f3-9ab5-e8e8ed0890ac)
what was the fix for this? is this the reason there is only BS1 on the HF repo with the precompiled modules?

**Comment by Shaistrong** [comment]
UPDATE, changed the compile code a little- I'm currently compiling for BS 1 16 res 64 2048. will update here if this will work on the refiner too.

**Comment by hlky** [comment]
Sorry, I am no longer active, my account is pending deletion. All I can tell you is that profilers, and batch size >1 modules, compile without issue on my machine, and your screenshot does not provide any useful information. You do not need to make any changes, and would suggest that you do not make changes unless you know what you are doing.

**Comment by Shaistrong** [comment]
> Sorry, I am no longer active, my account is pending deletion. All I can tell you is that profilers, and batch size >1 modules, compile without issue on my machine, and your screenshot does not provide any useful information. You do not need to make any changes, and would suggest that you do not make changes unless you know what you are doing.

the `compile_sdxl.py` file couldn't do batch size>1. I did manage to use it for bs 1 though. I think I might have figured out how to fix it.

**Comment by hlky** [comment]
I would suggest leaving this task to someone else, I believe FizzleDorf is in the process of compiling modules including a fix for 8px increment.

**Comment by Shaistrong** [comment]
figured it out, I compiled modules for xl and xlr in sm80, res64-2048, bs1-4. also sent them to FizzleDorf. might be added to the repo with the precompiled modules.
