### ISSUE TITLE
issue: compatibility patch required

### ISSUE THREAD

**Issue by ltdrdata** [FizzleDorf/AIT#51]
https://github.com/FizzleDorf/AIT/blob/d544b7b928be1e64c736ba137bb278d342073978/AITemplate/AITemplate.py#L348

`ModelPatcher` is moved to separated file(`comfy/model_patcher.py`) from `comfy/sd.py`

https://github.com/FizzleDorf/AIT/issues/48

**Comment by jags111** [comment]
Any idea how the modification to the same be accomplished or a revised AITemplate.py will help I feel. Can the same be updated as error trying the same.

**Comment by FizzleDorf** [comment]
resolved in f74366c
